### ISSUE TITLE
line ending symbols bug

### ISSUE THREAD

**Issue by NANI-SORE** [aziznal/dart-import-sorter#44]
When looking for app name extension splits package.yaml by '/n', but does not remove '/r' therefore breaking app name detection
i.e. 'name: app_test' becomes 'app_test/r'

I fixed it by wrapping return in ```getProjectNameFromPubspecFile``` with ```Utils.removeNewLines```

![image](https://user-images.githubusercontent.com/12685712/184149985-241ac124-6edd-4121-b22b-62b20c7eeb0a.png)

**Comment by aziznal** [comment]
I see. I appreciate your contribution. Would you like to create a PR with the fix? Your name will appear in the contributors section that way.

**Comment by NANI-SORE** [comment]
Sure, pushed a PR here
https://github.com/aziznal/dart-import-sorter/pull/45
