### ISSUE TITLE
Breaks multiline imports

### ISSUE THREAD

**Issue by talski** [aziznal/dart-import-sorter#48]
This import gets messed up after running sort

```
import 'package:flutter_web_plugins/flutter_web_plugins.dart'
    if (dart.library.io) 'package:app_name/fake_url_strategy.dart';
```

**Comment by aziznal** [comment]
Thank you for your feedback. I'll make it so that everything after the `if` is ignored when sorting. That should help. I'll work on a new release this weekend.

**Comment by aziznal** [comment]
Let's keep on tracking this in #49
