### ISSUE TITLE
Duplicating imports

### ISSUE THREAD

**Issue by JCKodel** [aziznal/dart-import-sorter#53]
I have these two files:

`index.dart`

```dart
library solid_repositories;

import 'package:flutter/foundation.dart';

part 'i_authentication_repository.dart';
```

`i_authentication_repository.dart`

```dart
part of solid_repositories;

@immutable
abstract class IAuthenticationRepository {}
```

Whenever the sort is triggered, it duplicates the `import 'package:flutter/foundation.dart';`:

```dart
library solid_repositories;

import 'package:flutter/foundation.dart';

import 'package:flutter/foundation.dart';

part 'i_authentication_repository.dart';
```

```

**Comment by aziznal** [comment]
Interesting. Perhaps it has to do with the `library` or `part` statements as I haven't really added any support for those. I'll do some digging and see if I can't release a fix soon. Thanks for your feedback.

**Comment by aziznal** [comment]
Turns out this has nothing to do with `library` or anything similar. It's just some sort of edge case where there are lines before the first import statement. I've pinpointed where and how the issue is happening. shouldn't be too difficult to solve.

**Comment by aziznal** [comment]
@JCKodel I've released an update which should hopefully fix the duplicating issue. Let me know if it fixes the issue so we can close it.

**Comment by JCKodel** [comment]
Working fine, thanks.
